### ISSUE TITLE
Have Questions in  Installing  tensorflow-compression

### ISSUE THREAD

**Issue by mia-7** [RenYang-home/OpenDVC#11]
Using pip install compression-1.0.tar.gz    

`Processing ./compression-1.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/user058/software/anaconda3/envs/CYJN/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-iq30nor1/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-iq30nor1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-tw2692z4
         cwd: /tmp/pip-req-build-iq30nor1/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/user058/software/anaconda3/envs/CYJN/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-iq30nor1/setup.py'
    ----------------------------------------
WARNING: Discarding file:///home/user058/CYJ/Open/OpenDVC-master/compression-1.0.tar.gz. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`
could you help me see what ‘s wrong about it？ Thank you very much！
In addition, I wanna know your python version.  Hoping you can tell me.  Thank you .

**Comment by RenYang-home** [comment]
Please try to directly download from https://github.com/tensorflow/compression/releases/tag/v1.0
And put the folder tensorflow-compression in the root directory.

**Comment by mia-7** [comment]
Thanks for your reply.

I directly download compression-1.0.tar.gz from https://github.com/tensorflow/compression/releases/tag/v1.0,lt’s still wrong.

 I put the compression.tar.gz in the  same directory as the codes,using python 3.6.
please forgive my innocence.I know it recently.could you say it more detailed latterly if you are convenient？

**Comment by RenYang-home** [comment]
You should uncompress tar.gz to a folder

**Comment by mia-7** [comment]
Yes, I also tried, but I can’t perform the .configure document, or make /make install instruction .
So I tried using pip install.

**Comment by RenYang-home** [comment]
Just putting the folder in the root directory of the codes will be fine, no need to install/make anything.

**Comment by mia-7** [comment]
Ok,I think I get it.I will try it again in the morning.
thank you for your comprehensive reply.

**Comment by mia-7** [comment]
Ok,I think I get it.I will try it again in the morning.
thank you for your comprehensive reply.

**Comment by mia-7** [comment]
I solved it.
thank you for you help.

**Comment by mia-7** [comment]
Sorry,I got a new problem.
When I run the OPenDVC-test-video.py, it shows ‘module tensorflow-compression has no attribute signalcon2d’.   how can I solve it？

**Comment by RenYang-home** [comment]
What version of TensorFlow do you use? It currently only support tf 1.12. Higher versions are not compatible.

**Comment by mia-7** [comment]
I use tensorflow 1.12. I solved it.it’s a directory problem.
thank you.
And should the libbpg.tar.gz be installed？

**Comment by RenYang-home** [comment]
Good to hear that. Yes, libbpg.tar.gz should be installed (follow the readme in https://github.com/mirrorer/libbpg), and include it into ~/.bashrc (if ubuntu)

**Comment by mia-7** [comment]
Hello,I followed the readme,but it meets error in the first step.

> 
(CYJN) [user058@node05 libbpg-0.9.8]$ make
make -C x265.out/12bit
make[1]: Entering directory `/home/user058/CYJ/Open/OpenDVC-master/libbpg-0.9.8/x265.out/12bit'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory `/home/user058/CYJ/Open/OpenDVC-master/libbpg-0.9.8/x265.out/12bit'
make: *** [x265_make] Error 2
> 
do you know the reason？My env is in a Linux server,and non-root directory makes the installation hard. Do you have some good solution？I will appreciate it .

**Comment by RenYang-home** [comment]
I am not so sure what leads to this error. Maybe you need to contact the support of BPG. It is out of the scope of OpenDVC.

**Comment by mia-7** [comment]
Ok,fine.

**Comment by mia-7** [comment]
Hello,I want to ask you a question. 
What  kind of entopy code model in your OpenDVC-test-p-frame"？the factorized code Model？I wanna to know the entropy difference between the DVC and OpenDVC.I will appreciate that if you can give me some suggestion. Thank you .

**Comment by RenYang-home** [comment]
Yes, we use the factorized model in OpenDVC, but the original DVC uses the hyperprior model. Replacing the entropy model in OpenDVC by a hyperprior model is also possible, but we haven't done that. If you want to significantly improve the coding efficiency, please consider our RLVC model, which uses a recurrent entropy model taking advantage of temporal correlation. RLVC is at https://github.com/RenYang-home/RLVC, with the paper at https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9288876

**Comment by mia-7** [comment]
Thank you for your reply and suggestion. It’s a new idea for me. I will consider it. Thank you.

**Comment by RenYang-home** [comment]
If there is no more question, I currently close this issue. Please feel free to reopen it if there are more questions.
