### ISSUE TITLE
why not create a requirements.txt

### ISSUE THREAD

**Issue by zjykzj** [RenYang-home/OpenDVC#12]
Hi @RenYang-home ， nice work!!!
I am a beginner of video compression, thank you very much for your open source, but there was also some problems when i want to create env for OpenDVC

## Problems recur

I create a new env for OpenDVC:

```
$ conda create -n compression python=3.8
```

Install tensorflow

```
$ pip install tensorflow-gpu==1.12
Looking in indexes: https://pypi.doubanio.com/simple
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.12
ERROR: No matching distribution found for tensorflow-gpu==1.12
```

## Advice

why not create a requirements.txt

## How to create it

first install pigar

```
$ pip install pigar
```

second use it to create requirements.txt

```
# execute in the root directory
$ pigar
```

**Comment by zjykzj** [comment]
In addition, I would like to know what version of Python you are currently running? python 3.6? / 3.7? / 3.8?

**Comment by RenYang-home** [comment]
Thanks for the suggestion. Any python version which is compatible with tensorflow 1.12 is fine, e.g. python 3.5/3.6. Python 3.8 seems to be only compatible with tensorflow 2

**Comment by zjykzj** [comment]
> Thanks for the suggestion. Any python version which is compatible with tensorflow 1.12 is fine, e.g. python 3.5/3.6. Python 3.8 seems to be only compatible with tensorflow 2

enen, i create a new env for python 3.6.13. can not install tensorflow 1.12, use python 3.6.5 is fine for me

```
$ conda create -n tensorflow python=3.6.5
$ conda activate tensorflow
$ pip install tensorflow==1.12
```
