### ISSUE TITLE
A difference between PSNR training code and test code

### ISSUE THREAD

**Issue by mmSir** [RenYang-home/OpenDVC#16]
In OpenDVC_train_PSNR.py
https://github.com/RenYang-home/OpenDVC/blob/f68b2ae4aa406cf51123780f06cbf21fd0f8fe19/OpenDVC_train_PSNR.py#L79
In OpenDVC_test_P-frame.py
https://github.com/RenYang-home/OpenDVC/blob/f68b2ae4aa406cf51123780f06cbf21fd0f8fe19/OpenDVC_test_P-frame.py#L81

Reconstructed Frame is clipped in test code but is trained without being cliped. Why not clip during training? Will it make a big difference?

**Comment by RenYang-home** [comment]
Because clip is not differentiable, so we didn't use that in training. But when inference, we intend to get a video in the range of [0, 255] with the unit8 format, so we clip it and save as unit8 png files.

**Comment by mmSir** [comment]
I get it.
Thanks for your reply!
