### ISSUE TITLE
Which validation dataset is used for the pre-trained models?

### ISSUE THREAD

**Issue by heydarshahi** [RenYang-home/OpenDVC#17]
I wonder whether you have used the training/validation split that is included in the Vimeo-90k dataset or used the whole dataset to train the published pre-trained models? 

Since the `find(pattern, path)` script defined [here](https://github.com/RenYang-home/OpenDVC#preperation-1) results in `folders.npy` containing _all_ sequences in Vimeo-90k, it seems training is done on the whole dataset. If this is true, then what dataset is used for validation?

**Comment by RenYang-home** [comment]
Thanks for the comment. For simplification, we didn't have the validation phase, but yes, it is better to use some other public datasets for validation
