### ISSUE TITLE
Training Iterations

### ISSUE THREAD

**Issue by heydarshahi** [RenYang-home/OpenDVC#18]
How did you decide on a good time to terminate the training? Did you try different checkpoints, or did you use some kind of evaluation on a different dataset?

Thanks!

**Comment by RenYang-home** [comment]
The best way would be testing on a validation set frequently during training to check if the model convergences. But in our codes, we just set the terminate time empirically, when observing the convergence on the training performance.

**Comment by heydarshahi** [comment]
I see...Thanks for the response!
