### ISSUE TITLE
Will you release the training code

### ISSUE THREAD

**Issue by jq-Lin** [RenYang-home/OpenDVC#2]

**Comment by RenYang-home** [comment]
Yes, we will release the training codes in the near future. Please give me an email address and I will send you a draft training code before the official release.

**Comment by jq-Lin** [comment]
thanks  a lot! This is a grate work
1126350832@qq.com  Looking forward to hearing from you

**Comment by yitong91** [comment]
Dear author, could you also send me the draft training code? I am sooo interested in your work and cannot wait :) . My email is yl3029@columbia.edu

**Comment by RenYang-home** [comment]
I sent the draft code to your emails. The final release will be done very soon.

Thanks,
Ren Yang

**Comment by felipecode** [comment]
Hello, I am also interested in the training code draft !
Same for the other two repos that you have
https://github.com/RenYang-home/HLVC
https://github.com/RenYang-home/RLVC
[EDIT] Thanks a lot for sharing the code !

Your work is super important for the community !There are
almost no training codes for video compression out there.

Thanks

**Comment by RenYang-home** [comment]
> Hello, I am also interested in the training code draft !
> Same for the other two repos that you have
> https://github.com/RenYang-home/HLVC
> https://github.com/RenYang-home/RLVC
> 
> [felipe.alcm@gmail.com](mailto:felipe.alcm@gmail.com)
> 
> Your work is super important for the community !There are
> almost no training codes for video compression out there.
> 
> Thanks

I sent a draft training code to your email. We will release the final version here very soon. 

For training HLVC, please simply copy the network part from HLVC test codes to this training code, and just replace training=True to False. We may also release it on GitHub, but it depends on my schedule.

The RLVC is still in submission, we will release its codes upon acceptance.

**Comment by RenYang-home** [comment]
I released the training codes. If you find any bug during training or have any question, please do not hesitate to contact me. Thanks!
