### ISSUE TITLE
about motion_flow

### ISSUE THREAD

**Issue by ddddm-pr** [RenYang-home/OpenDVC#21]
Hello,  thanks for ur open resource of the OpenDVC. I'm a beginner in end-to-end video compression, may I ask a simple question？
the pre-trained models of optical flow  is trained by youself or using spynet's weights?

**Comment by RenYang-home** [comment]
Hi, I pre-trained it myself, using the same training set as our method

**Comment by ddddm-pr** [comment]
Thanks a lot
