### ISSUE TITLE
About BPG tool

### ISSUE THREAD

**Issue by JiangYiCheng66** [RenYang-home/OpenDVC#24]
Following the installation instructions for bpg-0.9.8, ’make‘ or ‘make install‘ on linux does not seem to work, and in addition, I would like to know how to execute the bpgenc command line on windows.

**Comment by RenYang-home** [comment]
Hi,

Please check this link for instructions on both Linux and Windows: https://github.com/mirrorer/libbpg

**Comment by JiangYiCheng66** [comment]
Thank you for your help, now I have encounterd one more question, it s seems that paramter --path_com BasketballPass_dec_PSNR_1024 of  OpenDVC_test_video_decoder.py should be --path_com BasketballPass_com_PSNR_1024?

**Comment by RenYang-home** [comment]
You can put decoded images in a separate folder. Does it lead to any error?

**Comment by WenBingo** [comment]
> Following the installation instructions for bpg-0.9.8, ’make‘ or ‘make install‘ on linux does not seem to work, and in addition, I would like to know how to execute the bpgenc command line on windows.

hello，the code in readme.
bpgenc -f 444 -m 9 im1.png -o im1_QP27.bpg -q 27
bpgdec im1_QP27.bpg -o im1_bpg444_QP27.png

in the " bimeo_septuplet " it has many m1.png , what shloud i do  ? please
