### ISSUE TITLE
question about "Training your own models"

### ISSUE THREAD

**Issue by WenBingo** [RenYang-home/OpenDVC#26]
bpgenc -f 444 -m 9 im1.png -o im1_QP27.bpg -q 27
bpgdec im1_QP27.bpg -o im1_bpg444_QP27.png    

in the " bimeo_septuplet  " it has many 1m1.png , how do i to do ?

**Comment by WenBingo** [comment]
i also download the [bpg-0.9.8-win64.zip](https://bellard.org/bpg/bpg-0.9.8-win64.zip)， but i do not kown how to use . Can you help me ?

**Comment by RenYang-home** [comment]
To train your models, you have to compress im1.png in all subfolders in vimeo.

**Comment by WenBingo** [comment]
Thanks for your answear。
I just learning the direction of video compression , so I do not how to compress im1.png  in all subfolders in vimeo.
Need to use the folder.npy to compress the im1.png?

**Comment by RenYang-home** [comment]
The folder.npy contains all subdirectories of every training sample (im1.png - im7.png), then every im1.png in all these subdirectories should be compressed by BPG to generate the training set.

**Comment by Jiaaaaaqwe** [comment]
how to utilize the folder.npy?

**Comment by RenYang-home** [comment]
It's used in the training codes as the directories of training samples.


Jiaaaaaqwe ***@***.***>于2024年1月7日 周日22:04写道：

**Comment by Jiaaaaaqwe** [comment]
The Vimeo90k dataset has ~90k 7-frame clips, we need to compress "im1.png" in each clip as I-frame. For example:
bpgenc -f 444 -m 9 im1.png -o im1_QP27.bpg -q 27
bpgdec im1_QP27.bpg -o im1_bpg444_QP27.png        
Could not read 'im1.png'
