### ISSUE TITLE
A liitle suggestions for README

### ISSUE THREAD

**Issue by wuyy1234** [RenYang-home/OpenDVC#3]
Hello, first thanks for ur open resource of the OpenDVC. My master project benifits a lot from ur contributions. But there is a tiny error in the README.md and hope u could modify it.
The examples in the README.md 
for examples:
```
python OpenDVC_test_video_decoder.py --path_bin BasketballPass_bin_PSNR_1024 --path_com BasketballPass_dec_PSNR_1024 --model PSNR --l 1024 --Height 240 --Width 416 --GOP 10 --frame 100
```
should be modified as 
```
python OpenDVC_test_video_decoder.py --path_bin BasketballPass_bin_PSNR_1024 --path_com BasketballPass_dec_PSNR_1024 --mode PSNR --l 1024 --Height 240 --Width 416 --GOP 10 --frame 100
```
because ```--model``` can't match the arguments.

besides, I hope u could update the Dependency because Tensorflow 1.12 may be too old for most of users to get access to.

Thanks, RenYang.

**Comment by RenYang-home** [comment]
Thanks for your suggestions! I have corrected the README. The pre-trained models are trained on an early version of bottleneck, i.e., tensorflow-compression 1.0, please refer to https://github.com/tensorflow/compression/releases. The version 1.0 is only compatible with Tensorflow 1.12. Therefore, our pre-trained models can only be used on Tensorflow 1.12

However, we released the training codes yesterday. In theory, if installing a higher version of bottleneck, "import tensorflow_compression as tfc" will import that higher version of bottleneck, which is compatible with the later versions of tensorflow. I will try if my training codes are working that way. After trying, I will update the README, and you can train your own models on the later versions of Tensorflow.
