### ISSUE TITLE
DVC with an Efficient Neural Network

### ISSUE THREAD

**Issue by prasangadhungel** [RenYang-home/OpenDVC#6]
Thank you for this open source implementation of DVC.
Our team has also pulled out similar work but with a minimized network but of equal capability. We have released our code and pre-trained models at: https://github.com/tukilabs/Video-Compression-Net

Thanks!

**Comment by RenYang-home** [comment]
Thanks for the information!Best,Ren-------- 原始邮件 --------发件人： PrasangaDhungel <notifications@github.com>日期： 2020年9月20日周日 17:22收件人： RenYang-home/OpenDVC <OpenDVC@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [RenYang-home/OpenDVC] DVC with an Efficient Neural Network (#6)
Thank you for this open source implementation of DVC.
Our team has also pulled out similar work but with a minimized network but of equal capability. We have released our code and pre-trained models at: https://github.com/tukilabs/Video-Compression-Net
Thanks!
