### ISSUE TITLE
Something wrong in Readme.md

### ISSUE THREAD

**Issue by Chen8023** [RenYang-home/OpenDVC#7]
1.
bpgenc -f 444 -m 9 im1.png -o im1_QP27.bpg -q 27
bpgdec im1_QP27.bpg -o **im1_bpg444_QP27.bpg**    

shoule be 

bpgenc -f 444 -m 9 im1.png -o im1_QP27.bpg -q 27
bpgdec im1_QP27.bpg -o **im1_bpg444_QP27.png**  

2.
python OpenDVC_test_video.py --path BasketballPass **--model** PSNR  --metric PSNR --l 1024
python OpenDVC_test_video.py --path BasketballPass **--model** MS-SSIM  --metric MS-SSIM --python python --CA_model_path ./CA_EntropyModel_Test --l 32

shoule be

python OpenDVC_test_video.py --path BasketballPass **--mode** PSNR  --metric PSNR --l 1024
python OpenDVC_test_video.py --path BasketballPass **--mode** MS-SSIM  --metric MS-SSIM --python python --CA_model_path ./CA_EntropyModel_Test --l 32

**Comment by RenYang-home** [comment]
Thank you so much. I have corrected the typos.

Best,
Ren
